version: '3'

services:
  apache1:
    container_name: apache1
    image: hh4huy/apache2:latest
    networks:
      - apache-net
    restart: on-failure

  apache2:
    container_name: apache2
    image: hh4huy/apache2:v1
    networks:
      - apache-net
    restart: on-failure

  apache3:
    container_name: apache3
    image: hh4huy/apache2:v2
    networks:
      - apache-net
    restart: on-failure

  nginx1:
    container_name: nginx1
    image: hh4huy/nginx:latest
    networks:
      - apache-net
    ports:
      - "80:80"
    restart: on-failure
    
networks:
  apache-net:
    driver: bridge
